### ISSUE TITLE
requiresFadingEdge or fadingEdge not work ?

### ISSUE THREAD

**Issue by minhvietattt** [rubensousa/DpadRecyclerView#119]
Hi, I had tried your example: 
`<com.rubensousa.dpadrecyclerview.DpadRecyclerView
        android:id="@+id/row_recyclerview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:clipChildren="true"
        android:gravity="center"
        android:minHeight="@dimen/hp_row_min_height"
        android:orientation="horizontal"
        android:requiresFadingEdge="horizontal|vertical"
        android:fadingEdge="horizontal|vertical"
        app:dpadRecyclerViewChildAlignmentFraction="0"
        app:dpadRecyclerViewFocusOutBack="false"
        app:dpadRecyclerViewFocusOutFront="false"
        app:dpadRecyclerViewParentAlignmentEdge="none"
        app:dpadRecyclerViewParentAlignmentFractionEnabled="false"
        app:dpadRecyclerViewParentAlignmentOffset="@dimen/hp_row_card_margin_start" />`
althought i had try to add attrs:
        android:requiresFadingEdge="horizontal|vertical"
        android:fadingEdge="horizontal|vertical"
but it not work. Any suggestion ?

**Comment by rubensousa** [comment]
Hey. There's no support for fading edges yet. See this: https://github.com/rubensousa/DpadRecyclerView/issues/18

It will be there in 1.1.0

**Comment by rubensousa** [comment]
@minhvietattt work for this started here: https://github.com/rubensousa/DpadRecyclerView/tree/fading_edge

Here's a preview:

<img width="884" alt="image" src="https://user-images.githubusercontent.com/10662096/232174120-5ce31f6e-1df0-47a1-8999-e584693331f2.png">

Accessible in the sample here: 


<img width="884" alt="image" src="https://user-images.githubusercontent.com/10662096/232174162-874243b3-d11e-4127-a88b-59a46df856f0.png">

I will add this in the next beta version instead, if it's stable enough. Feel free to give feedback

**Comment by rubensousa** [comment]
Released in `1.0.0-beta02`. @minhvietattt just add `fadingEdgeLength` or use the following APIs: https://rubensousa.github.io/DpadRecyclerView/migrating_leanback/#fading-edges

**Comment by minhvietattt** [comment]
Many thank for your support.
