### ISSUE TITLE
Can provide a light way fix RecyclerView items lose focus. help wanted!

### ISSUE THREAD

**Issue by mackwu828** [rubensousa/DpadRecyclerView#121]
If you long press the dpad down to scroll fast between the items sometimes the focus is lost to a view that isn't a child of the RecyclerView. like this:
https://stackoverflow.com/questions/34277425/recyclerview-items-lose-focus/48309162#48309162

I think the best way is to customize LayoutManager, like PivotLayoutManager. but it’s heavy for my old project using PivotLayoutManager. 

can u help provide a light way extend GridLayoutManager to fix focus issue on RecyclerView.

**Comment by rubensousa** [comment]
Why are you using GridLayoutManager if you need dpad navigation? I can't help in this case, since this isn't related to the library.
