### ISSUE TITLE
I don't get focus I don't know why. can anyone help me to solve this

### ISSUE THREAD

**Issue by pavelsust** [rubensousa/DpadRecyclerView#157]
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:focusable="true"
    android:layout_gravity="right"
    android:clipChildren="false">

    <com.rubensousa.dpadrecyclerview.DpadRecyclerView
        android:id="@+id/slider_recyclerView"
        android:layout_width="match_parent"
        android:orientation="horizontal"
        android:layout_height="match_parent"
        android:clipChildren="false" />

</androidx.constraintlayout.widget.ConstraintLayout>

    binding.sliderRecyclerView.requestFocus()
    binding.sliderRecyclerView.adapter = bannerAdapter

**Comment by rubensousa** [comment]
Please try following this guide: https://rubensousa.github.io/DpadRecyclerView/selection/

You need a focusable element in your adapter

**Comment by rubensousa** [comment]
@pavelsust did you manage to solve this problem?
