### ISSUE TITLE
focus item scroll unfriendly when itemCount less then the screen length

### ISSUE THREAD

**Issue by Nicky-Li** [rubensousa/DpadRecyclerView#160]
In horizontal state, when i change the number (the fun generateList() in  class ListViewModel ) is less than the screen length(such like 5), the focus item scroll unfriendly

**Comment by rubensousa** [comment]
Hi @Nicky-Li. Can you please explain in more detail what do you mean? Also a screen recording would help me understand better

**Comment by Nicky-Li** [comment]
i mean change the value(the fun generateList() in class ListViewModel ) in your demo app.
![demo](https://github.com/rubensousa/DpadRecyclerView/assets/1235623/38d163e2-d029-4484-b0f3-33e70fc308e9)

**Comment by rubensousa** [comment]
Hi @Nicky-Li. Thanks for the example. I see the problem now. Will address this in the upcoming version.

Please note this only happens if you set the parent alignment edge to `max`. So you can fix this by using `min_max` instead, which should behave fine.

**Comment by rubensousa** [comment]
@Nicky-Li 
The fix is available in `1.1.0-beta01`
