### ISSUE TITLE
Scroll jumps to the top on item's layout update

### ISSUE THREAD

**Issue by IvanPosohov** [rubensousa/DpadRecyclerView#171]
Hi! 
I've got an issue on device supporting touch navigation.

PREREQUIRENMENTS:
1) sample.ui.screen.list.ListFragment:89 add 
    binding.recyclerView.setFocusSearchDisabled(true)
2) sample.ui.widget.item.ItemViewHolder:42 add 
    textView.updateLayuotParams<FrameLayout.LayoutPrams> { width = LayoutParams.WRAP_CONTENT }

STEPS TO REPRODUCE:
1) Run sample app
2) Click Nested
3) Scroll down a little with touch
4) Click on any item

EXPECTED:
- scroll position does not change

ACTUAL:
- scrolled to the top

https://github.com/rubensousa/DpadRecyclerView/assets/3154084/0c6182c8-a4b5-4b2d-ba56-5afd87367514

**Comment by rubensousa** [comment]
Hi @IvanPosohov. Can you share more details on how and why you're using DpadRecyclerView for touch events as well? Just to satisfy my curiosity. I will address this bug regardless

**Comment by IvanPosohov** [comment]
Hi! Thx for response!
My app is running on the vendor's devices and one of them has screen on it. I don't want to support two different layouts for screen and no-screen devices

**Comment by rubensousa** [comment]
That makes sense. So this means you would prefer a setup that works with touch events, but completely ignores alignment configurations during touch events, correct?

**Comment by IvanPosohov** [comment]
Yep, something like 
`if (deviceWithScreen) { dpadRecyclerView.setTouchMode(true) }`

**Comment by rubensousa** [comment]
I would try for a different approach, since I know that automotive projects might require both DPAD events and touch events depending on who's interacting with the device. Since this is a bit more tricky, I will need more time to investigate a proper solution. Since you already tried `setFocusSearchDisabled`, I might hijack that flag to satisfy your use case temporarily. Would that be fine for you?

**Comment by IvanPosohov** [comment]
Yes, I think it would be ok

**Comment by rubensousa** [comment]
@IvanPosohov fix released in `1.2.0-alpha02`
