### ISSUE TITLE
Vertical list with focus centered

### ISSUE THREAD

**Issue by smin9** [rubensousa/DpadRecyclerView#177]
Hello, I encountered a problem, I set
`recyclerView.setParentAlignment(
ParentAlignment(fraction = 0.5f)
)
recyclerView.setChildAlignment(
ChildAlignment(fraction = 0.5f)
) `
to center the focus, but
I want that when the remote control is pressed, when the next item in the list gets focus, it does not get focus on the first item, but gets focus right below it. What should I do?
![WechatIMG76](https://github.com/rubensousa/DpadRecyclerView/assets/14284935/4aa8d16e-615f-402c-ba0e-86000ef90ef3)

**Comment by rubensousa** [comment]
Hi @smin9. To achieve this, you have 2 alternatives:
1. Set the edge alignment parameter to `NONE`: https://rubensousa.github.io/DpadRecyclerView/alignment/#aligning-to-an-edge
2. Intercept the focus change in the root layout and find the center position manually.

Approach 2 is more complex and requires manual work, but it's definitely possible. Anyway, I would really avoid deviating too much from the default behaviours for UX consistency.

**Comment by rubensousa** [comment]
@smin9 closing this since this is already supported
