### ISSUE TITLE
Touch behavior in scrolling

### ISSUE THREAD

**Issue by HarshaliSachani** [rubensousa/DpadRecyclerView#184]
Can we use this lib for mobile app as well? 
It works perfect for Leanback focus and scrolling behavior in TV devices but I want to use same recycler view for support Mobile device scrolling and touch behavior

**Comment by rubensousa** [comment]
Hi @HarshaliSachani 

Can you explain why you want to use this library for a mobile app? Which feature are you missing from the standard RecyclerView library?

**Comment by HarshaliSachani** [comment]
@rubensousa 
Standard recycler view is perfect there is no issue with it. But I wanted to use same app in TV and mobile. As in this library you used recycler view instead of Leanback gridview and modify layout manager to handle focus and scrolling behaviour in nested recyclerview and gridview. So I tried to use the dpad recycler view on mobile devices with touch scrolling behaviour. Can we use it or is there any way to support it in mobile as well?

**Comment by rubensousa** [comment]
@HarshaliSachani any update here?

**Comment by rubensousa** [comment]
Added `DpadSelectionSnapHelper` that helps with this in `1.3.0-alpha04`
