### ISSUE TITLE
How to implement StaggeredGridLayout?

### ISSUE THREAD

**Issue by RavioliWonton** [rubensousa/DpadRecyclerView#190]
Hi, first of all thank you for your tremendous job on this library.
I have a problem here, my android tv project contain a page that fixed number channel logos arranged in grid on the right side, and left side have a livesteam view same height as grid. When user select channel right side, left side big view should show corresponding channel livestream. something like this:
![image](https://github.com/rubensousa/DpadRecyclerView/assets/13551245/d1fafc88-cd5b-45b3-8d82-de6a0950c5cf)

I want implement it using this great library, but after read through the doc and serveal failed attempt, I still can't make one thing out: determine how to arrange this layout. If I using one view to rule them all, I cannot set the left view size and postion that they can look like above, because doc said that I cannot change the layout manager, and existing api couldn't arrange seprate viewholder postion.If I using one livestream view and one recyclerview for the grid, then I can't make the whole screen scrollable and make focus consistant because I cannot using RecyclerView inside NestedScrollView or other ScrollView (it's not best practise, unless heavilly modify the source code).

So could you please kindly help me figure this out or provide some api that I can use the staggered grid layout? Thank you.

**Comment by rubensousa** [comment]
I would recommend 2 different components: one big component for the stream and a separate one for the grid. You can use constraint layout to constrain each component to 50% of the screen width or something like that.

This library was not built for use cases like these unfortunately.

I recommend this layout structure for this case if you need scrollable content:

```
- Vertical DpadRecyclerView
   - CustomHorizontalLayout with ConstraintLayout
       - LiveStreamComponent
       - GridComponent (DpadRecyclerView)
```

Please let me know if this was useful

**Comment by RavioliWonton** [comment]
Thank you for your help, I will give it a try.

**Comment by RavioliWonton** [comment]
It works like a charm! Thank you for your great help!
I have two more question: 
1. How can I disable the default selection? I want the grid have no choice at first until user turn their focus on it.
2. I find alignment function part of this library (and the explaination of the documentation) a little bit incomprehensible, my understanding is that [Child Alignment](https://rubensousa.github.io/DpadRecyclerView/alignment/#child-alignment) is to determine where are the anchors of the viewholders, but what about [Parent Alignment](https://rubensousa.github.io/DpadRecyclerView/alignment/#parent-alignment)? Is it define the anchor of the whole list (or grid) to alignment with the parent view (which means DpadRecyclerView itself) ? If so, why should I not simply add a header or footer to achieve the same goal (as far as I concerned)? Also I have a little confuse about the api arguments, what does [includingPadding](https://github.com/rubensousa/DpadRecyclerView/blob/master/dpadrecyclerview/src/main/java/com/rubensousa/dpadrecyclerview/ChildAlignment.kt#L29C18-L29C32) and [alignToBaseline](https://github.com/rubensousa/DpadRecyclerView/blob/master/dpadrecyclerview/src/main/java/com/rubensousa/dpadrecyclerview/ChildAlignment.kt#L30) mean? There are no documentation about this and I read through the source code still cannot figure it out.

Please forgive my bad English, hope hearing from you soon.

**Comment by rubensousa** [comment]
Hi. I'm glad I could help.

Regarding your points:

> How can I disable the default selection? I want the grid have no choice at first until user turn their focus on it.

Currently, this is not possible. You can ignore doing something on selection changes without focus by checking if the `recyclerview.hasFocus` is false, if that's what you're looking for.

> but what about [Parent Alignment](https://rubensousa.github.io/DpadRecyclerView/alignment/#parent-alignment)?

Please check the recipes here: https://rubensousa.github.io/DpadRecyclerView/recipes/alignment/

Let me know if these docs are not enough and I will try to add them in the near future.

**Comment by RavioliWonton** [comment]
Thank you, my problems are solved at all!

**Comment by RavioliWonton** [comment]
@rubensousa Sorry to bother you again but I have another little question here.
I use ConcatAdapter to support multiple data source in the outer vertical DpadRecyclerView (like the picture above and the structure you mentioned in your comment).
If I navigate from left side LiveStreamComponent, I can scroll to next item (consider this as a list, like your [blog post second video shows](https://rubensousa.com/2022/11/08/dpadrecyclerview/)) and choose child item normally, but if I use dpad to navigate down from right side, the whole view lost all focus, I need move focus out of fragment and move in again so I can gain focus again. 
Could you please help me fix this issue?
