### ISSUE TITLE
Scrolling issue when loading images in onBindViewHolder

### ISSUE THREAD

**Issue by Anuragjain01** [rubensousa/DpadRecyclerView#207]

**Comment by rubensousa** [comment]
Hello. Can you please provide detailed information for this issue? I can't help without more about what's wrong

**Comment by Anuragjain01** [comment]
Hi @rubensousa  i am using DpadRecylerView  demo also using in my project untill i  did not use image on card its working fine but when i added image 
In itemViewHolder in your sample. getting stuck 
textView?.text = item.toString()
      imageView?.let {
          Glide
                .with(it.context)
                .load("https://raw.githubusercontent.com/Anuragjain01/image_folder/main/01.png")
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .skipMemoryCache(false)
                .centerCrop()
                .into(it)
                

https://github.com/rubensousa/DpadRecyclerView/assets/164026007/a06287be-e141-41a5-a31b-6e0ef6861ba1


                
                

https://github.com/rubensousa/DpadRecyclerView/assets/164026007/e1e251fc-4816-4849-a57d-37c11f305ff9

**Comment by rubensousa** [comment]
Can you please commit that state to your fork and share the link here? I will have a look, but it looks like your `onBindViewHolder` calls are too heavy

**Comment by homayoonahmadi** [comment]
Hi there, I can confirm this behavior, I'm seeing it in my project too

**Comment by homayoonahmadi** [comment]
I have a grid of items with spanCount that includes section headers, this happens when I navigate between sections (especially when I go up), but inside a section (if the section has multiple rows) it doesn't happen

**Comment by rubensousa** [comment]
@homayoonahmadi can you share a sample that reproduces the issue?

**Comment by rubensousa** [comment]
@homayoonahmadi @Anuragjain01 Can you please try this: `setLayoutWhileScrollingEnabled(false)` and let me know if it solves the issue?

**Comment by rubensousa** [comment]
@homayoonahmadi @Anuragjain01 please try out `1.3.0-alpha03` and let me know if the issue is still there. If that's the case, I'm going to need a sample because I couldn't reproduce this
