### ISSUE TITLE
How can I bind the selected state to the holder content?

### ISSUE THREAD

**Issue by ChinaSunHZ** [rubensousa/DpadRecyclerView#243]
Background Info:  
 - Have a data repository, interval 10s auto update items to adapter
 - Unselected item height = 10, selected item height = 20, also set new values to background / text size ....

For example:
```
--------
1
2
3 -> Current selected
4
5
--------

data updating...

------
2
4
5
6
1
3 -> Still select this holder
8
------

remove 3 

------
2 -> auto selected first item
1
6
8
4
5
7
------
```

Currently:  I used method `setSelectedPosition` to manually set the position, but after the data changed, it still could not accurately selected the required position

```kotlin
private fun setNewItemsAndKeepSelectedPositionForCurrentItem(items: MutableList<Item>) {
    val rvList = binding.rvList

    val currentSelectedPosition = rvList.getSelectedPosition()
    if (rvList.hasFocus() && currentSelectedPosition >= 0) {
        val targetSelectedItem = adapter.getItemOrNull(currentSelectedPosition)
        val targetSelectedItemsPosition = items.indexOfFirst { targetSelectedItem == it }

        adapter.setNewInstance(items)

        rvList.post {
            val realSelectedPosition =
                if ( targetSelectedItemsPosition < 0) {
                    0 // if current item remove in new data, auto jump to first item
                } else {
                    targetSelectedItemsPosition
                }
            rvList.setSelectedPosition(realSelectedPosition)
        }
    } else {
        adapter.setNewInstance(items)
    }
}
```

In addition, I also tried to use the `adapter.registerAdapterDataObserver.onChange()` method to change the position, but the position error still occurred.

So... I have no idea how to fix this, I've been trying for two days and it still doesn't work.

**Comment by rubensousa** [comment]
Are you using `ListAdapter`? There is a callback for adapter changes that you should use.
You can also register a layout complete listener to `DpadRecyclerView` and then update the selection there: 

https://rubensousa.github.io/DpadRecyclerView/api/dpadrecyclerview/com.rubensousa.dpadrecyclerview/-dpad-recycler-view/add-on-layout-completed-listener.html

Please let me know if it worked

**Comment by ChinaSunHZ** [comment]
> Are you using `ListAdapter`? There is a callback for adapter changes that you should use. You can also register a layout complete listener to `DpadRecyclerView` and then update the selection there:
> 
> https://rubensousa.github.io/DpadRecyclerView/api/dpadrecyclerview/com.rubensousa.dpadrecyclerview/-dpad-recycler-view/add-on-layout-completed-listener.html
> 
> Please let me know if it worked

After my attempts `layout complete listener` this method still has the problem of position error.

The app adapter extends from BaseQuickAdapter
[io.github.cymchad:BaseRecyclerViewAdapterHelper:3.0.14](https://github.com/CymChad/BaseRecyclerViewAdapterHelper)

But I think this may not have much to do with the adapter, because the position of the data is also obtained through indexOf.

```kotlin
private fun setNewItemsAndKeepSelectedPositionForCurrentItem(items: MutableList<Item>) {
    val rvList = binding.rvList

    val currentSelectedPosition = rvList.getSelectedPosition()
    val targetSelectedItem = adapter.getItemOrNull(currentSelectedPosition)
    targetSelectedItemsPosition = items.indexOfFirst { targetSelectedItem == it }

    adapter.setNewInstance(items)
}

override fun onLayoutCompleted(state: RecyclerView.State) {
    if (targetSelectedItemsPosition == -1) return
    binding.rvList.setSelectedPosition(targetSelectedItemsPosition)
}
```

**Comment by rubensousa** [comment]
What do you mean by "position error" exactly? Can you please describe the problem?

**Comment by ChinaSunHZ** [comment]
> What do you mean by "position error" exactly? Can you please describe the problem?

For example:
Currently I use down / up event to set the focus to position = 3 (content is 3), then the data in the list is updated, the content of position = 3 becomes 5, and the actual position of the item with content 3 becomes position = 7, then the focus should be set to position 7 (content is 3) through setSelectedPosition. However, the positioning position is wrong. It is positioned to another position.

After my testing, this seems to be related to item decoration, which makes me very strange.

You can try this code, list render completed and then trigger key event change focus to random position. 
And remove `addItemDecoration()` method retry it.

[Dpad Test Project](https://github.com/ChinaSunHZ/Dpad/blob/master/app/src/main/java/com/spencer_dev/dpad/IntervalRefreshActivity.kt#L41)

**Comment by rubensousa** [comment]
@ChinaSunHZ thanks for the sample. I will take a look at it

**Comment by rubensousa** [comment]
@ChinaSunHZ here is a PR that solves your issue: https://github.com/ChinaSunHZ/Dpad/pull/1

You have 2 sources of the selection: one driven by `DpadRecyclerView` and then one for your adapter changes. You need to make sure those are in sync. In that PR I keep the selected item and ensure that `onBind` passes the correct selection state.

I'm closing this issue since this is not a problem with the library

**Comment by ChinaSunHZ** [comment]
> @ChinaSunHZ here is a PR that solves your issue: [ChinaSunHZ/Dpad#1](https://github.com/ChinaSunHZ/Dpad/pull/1)
> 
> You have 2 sources of the selection: one driven by `DpadRecyclerView` and then one for your adapter changes. You need to make sure those are in sync. In that PR I keep the selected item and ensure that `onBind` passes the correct selection state.
> 
> I'm closing this issue since this is not a problem with the library

I saw the PR and your changes are valid. Thank you so much! Let me see why.

**Comment by ChinaSunHZ** [comment]
> @ChinaSunHZ here is a PR that solves your issue: [ChinaSunHZ/Dpad#1](https://github.com/ChinaSunHZ/Dpad/pull/1)@ChinaSunHZ这里有一个 PR 可以解决您的问题： [ChinaSunHZ/Dpad#1](https://github.com/ChinaSunHZ/Dpad/pull/1)
> 
> You have 2 sources of the selection: one driven by `DpadRecyclerView` and then one for your adapter changes. You need to make sure those are in sync. In that PR I keep the selected item and ensure that `onBind` passes the correct selection state.
> 
> I'm closing this issue since this is not a problem with the library

Thank you very much for the PR, I'm trying out the code from that PR.
Thanks again!
