### ISSUE TITLE
issue while scrolling top to button and left to right 

### ISSUE THREAD

**Issue by Anuragjain01** [rubensousa/DpadRecyclerView#250]
Hi @rubensousa  i am getting one issue that when i am pressing top to button and left to right on same time then untill my focus settle up my horizontal rail scroll. 
please check attachment 

https://github.com/user-attachments/assets/2788d8a9-2301-40b2-adee-4afe0b7a8594

**Comment by rubensousa** [comment]
@Anuragjain01 this is working as intended and it's not an issue. When you scroll up or down, focus is immediately sent to the nested `DpadRecyclerView`. 

If you really want that behavior, you need to attach a scroll listener to the parent `DpadRecyclerView` and then enable/disable scrolling of the nested `DpadRecyclerView` based on the current scroll state of the parent one. This is achievable with some minor effort, so I won't add this feature to the library
